# Generated by Django 3.0.7 on 2020-07-15 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=50, verbose_name='author')),
                ('timeStamp', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
