# Generated by Django 3.0.7 on 2020-07-16 13:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0003_auto_20200715_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(max_length=50, verbose_name='slug'),
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False, verbose_name='sno')),
                ('comment', models.TextField(verbose_name='comment')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='Time')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.BlogComment', verbose_name='parent')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.Post', verbose_name='post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
