# Generated by Django 3.0.7 on 2020-07-12 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200712_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='timeStamp',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='DateTime'),
            preserve_default=False,
        ),
    ]
